version: '3.9'

services:
  production_webapp:
    container_name: production_webapp
    image: production
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'